package emit

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"property_sync/psync/internal/ir"
	"property_sync/psync/internal/wire"
)

var protoScalar = map[string]string{
	"bool": "bool", "int": "int64", "int8": "int64", "int16": "int64", "int32": "int64", "int64": "int64",
	"uint8": "uint64", "uint16": "uint64", "uint32": "uint64", "uint64": "uint64",
	"float": "float", "double": "float", "string": "string",
}

type emitField struct {
	Index       int
	Name        string
	WireKind    string
	CppType     string
	ProtoType   string
	ItemClass   string
	ItemShort   string
	Flags       []string
	HasItemSync bool
}

type emitClass struct {
	Name          string
	Namespace     string
	SchemaVersion int
	Kind          string
	Fields        []emitField
	ProtoImports  []string
}

func (ec emitClass) cppNS() string          { return wire.NsCpp(ec.Namespace) }
func (ec emitClass) qualName() string       { return wire.Qual(ec.Namespace, ec.Name) }
func (ec emitClass) isBagItem() bool       { return ec.Kind == "bag_item" }
func (ec emitClass) isSlotItem() bool      { return ec.Kind == "slot_item" }
func (ec emitClass) isPropertyItem() bool  { return ec.Kind == "bag_item" || ec.Kind == "slot_item" || ec.Kind == "vec_item" }
func (ec emitClass) hasBagID() bool        { return ec.Kind == "bag_item" || ec.Kind == "slot_item" }

func protoTypeOf(t ir.TypeRef) string {
	switch t.Kind {
	case "scalar":
		n := deref(t.Name)
		if p, ok := protoScalar[n]; ok {
			return p
		}
		return "bytes"
	case "array":
		e := or(deref(t.Elem), "float")
		return "repeated " + or(protoScalar[e], e)
	case "list":
		e := or(deref(t.Elem), "string")
		return "repeated " + or(protoScalar[e], e)
	case "dict":
		k := or(deref(t.Key), "string")
		if k != "string" {
			k = or(protoScalar[k], k)
		} else {
			k = "string"
		}
		v := or(deref(t.Value), "string")
		v = or(protoScalar[v], v)
		return fmt.Sprintf("map<%s, %s>", k, v)
	case "bag", "vec":
		return "repeated " + deref(t.Name) + "Snapshot"
	case "slots":
		return deref(t.Name) + "SlotsSnapshot"
	case "object":
		return deref(t.Name) + "Snapshot"
	}
	return "bytes"
}

func buildEmitClass(cls *ir.ClassDef, legacyWire bool) emitClass {
	fields := append([]ir.FieldDef(nil), cls.Fields...)
	sort.Slice(fields, func(i, j int) bool { return fields[i].Index < fields[j].Index })
	var efs []emitField
	var imports []string
	seen := map[string]bool{}
	for _, f := range fields {
		w := wire.MapWire(f.Type.WireKind(), legacyWire)
		itemQ := wire.ItemClassOf(f.Type, cls.Namespace)
		itemShort := ""
		if f.Type.Kind == "bag" || f.Type.Kind == "slots" || f.Type.Kind == "vec" || f.Type.Kind == "object" {
			itemShort = deref(f.Type.Name)
		}
		hasSync := f.Type.Kind == "bag" || f.Type.Kind == "slots" || f.Type.Kind == "vec"
		if hasSync && itemShort != "" {
			imp := itemShort + ".proto"
			if !seen[imp] {
				seen[imp] = true
				imports = append(imports, imp)
			}
		}
		efs = append(efs, emitField{
			Index: f.Index, Name: f.Name, WireKind: w,
			CppType: wire.CppTypeOf(f.Type, cls.Namespace), ProtoType: protoTypeOf(f.Type),
			ItemClass: itemQ, ItemShort: itemShort, Flags: append([]string{}, f.Flags...),
			HasItemSync: hasSync,
		})
	}
	return emitClass{
		Name: cls.Name, Namespace: cls.Namespace, SchemaVersion: cls.SchemaVersion,
		Kind: cls.Kind, Fields: efs, ProtoImports: imports,
	}
}

func emitSchemaJSON(ec emitClass) map[string]any {
	fields := make([]map[string]any, len(ec.Fields))
	for i, f := range ec.Fields {
		fields[i] = map[string]any{
			"index": f.Index, "name": f.Name, "cpp_type": f.CppType,
			"wire_kind": f.WireKind, "item_class": f.ItemClass, "flags": f.Flags,
		}
	}
	return map[string]any{
		"class": ec.Name, "qualified_name": ec.qualName(),
		"namespace": ec.cppNS(), "schema_version": ec.SchemaVersion, "fields": fields,
	}
}

func emitFlagsLua(flags *ir.FlagsDef) string {
	if flags == nil {
		return "nil"
	}
	var bitParts []string
	for _, b := range flags.Bits {
		bitParts = append(bitParts, fmt.Sprintf("%s = %d", b.Name, b.Bit))
	}
	var aliasParts []string
	for _, a := range flags.Aliases {
		inner := make([]string, len(a.Expr))
		for i, x := range a.Expr {
			inner[i] = fmt.Sprintf("%q", x)
		}
		aliasParts = append(aliasParts, fmt.Sprintf("%s = { %s }", a.Name, strings.Join(inner, ", ")))
	}
	return "{ bits = { " + strings.Join(bitParts, ", ") + " }, aliases = { " + strings.Join(aliasParts, ", ") + " } }"
}

func emitLuaMeta(ec emitClass) string {
	var lines []string
	lines = append(lines,
		"-- Auto-generated by psync emit — do not edit.",
		"-- Property class metadata (fields / INDEX / wire_kind); Replay via property_runtime.",
		`local Runtime = require("property_runtime")`,
	)
	for _, f := range ec.Fields {
		if f.HasItemSync {
			lines = append(lines, fmt.Sprintf(`local %sMeta = require("%s_meta")`, f.ItemShort, f.ItemShort))
		}
	}
	lines = append(lines, "",
		"local M = {",
		fmt.Sprintf("  SCHEMA_VERSION = %d,", ec.SchemaVersion),
		fmt.Sprintf(`  CLASS_NAME = "%s",`, ec.Name),
		fmt.Sprintf("  has_slot = %s,", boolLua(ec.isSlotItem())),
		fmt.Sprintf("  has_bag_id = %s,", boolLua(ec.hasBagID())),
		"  fields = {",
	)
	for _, f := range ec.Fields {
		flagLit := make([]string, len(f.Flags))
		for i, x := range f.Flags {
			flagLit[i] = fmt.Sprintf("%q", x)
		}
		extra := ""
		if f.HasItemSync {
			extra = fmt.Sprintf(", item_meta = %sMeta.META", f.ItemShort)
		}
		lines = append(lines, fmt.Sprintf(
			`    { index = %d, name = "%s", wire_kind = "%s", flags = { %s }%s },`,
			f.Index, f.Name, f.WireKind, strings.Join(flagLit, ", "), extra,
		))
	}
	indexParts := make([]string, len(ec.Fields))
	for i, f := range ec.Fields {
		indexParts[i] = fmt.Sprintf("%s = %d", f.Name, f.Index)
	}
	lines = append(lines,
		"  },",
		fmt.Sprintf("  INDEX = { %s },", strings.Join(indexParts, ", ")),
		"}", "",
		"return Runtime.attach_meta(M)", "",
	)
	return strings.Join(lines, "\n")
}

func emitLuaRecord(ec emitClass, flags *ir.FlagsDef) string {
	return strings.Join([]string{
		"-- Auto-generated by psync emit — do not edit.",
		`-- Usage: local rec = require("Player_record").new(); rec.hp = 80; rec.tags:push("vip")`,
		`-- Or:    local data = Meta.new_default(); require("Player_record").open(data)`,
		`local Record = require("property_record")`,
		fmt.Sprintf(`local Meta = require("%s_meta")`, ec.Name),
		"",
		"local M = {}",
		fmt.Sprintf("M.FLAGS = %s", emitFlagsLua(flags)),
		"M.Meta = Meta",
		"",
		"function M.new(opts)",
		"  opts = opts or {}",
		"  opts.flags = opts.flags or M.FLAGS",
		`  opts.need_flag_names = opts.need_flag_names or { "sync_clients" }`,
		"  return Record.bind(Meta, opts)",
		"end",
		"",
		"--- Open over an existing 源表.",
		"function M.open(obj, opts)",
		"  opts = opts or {}",
		"  opts.obj = obj",
		"  return M.new(opts)",
		"end",
		"",
		"return M",
		"",
	}, "\n")
}

func emitProto(ec emitClass) string {
	var lines []string
	lines = append(lines,
		`syntax = "proto3";`,
		"// Auto-generated by psync emit — do not edit.",
		"// Field numbers: business = property index + 1 (proto forbids 0); schema_version = 1000.",
		"// Compatibility: only append fields; never reuse numbers. See docs/compatibility.md.",
		"",
		"package property_sync.generated;",
		"",
	)
	for _, imp := range ec.ProtoImports {
		lines = append(lines, fmt.Sprintf(`import "%s";`, imp))
	}
	if len(ec.ProtoImports) > 0 {
		lines = append(lines, "")
	}
	if ec.isPropertyItem() {
		lines = append(lines, "// Item / bag / slot / vec element snapshot")
	}
	lines = append(lines, fmt.Sprintf("message %sSnapshot {", ec.Name))
	lines = append(lines, "  uint32 schema_version = 1000;")
	if ec.isBagItem() {
		lines = append(lines, "  int64 id = 1; // index=0 bag key")
	}
	if ec.isSlotItem() {
		lines = append(lines, "  int64 id = 1; // index=0")
		lines = append(lines, "  uint32 slot = 2; // index=1")
	}
	for _, f := range ec.Fields {
		lines = append(lines, fmt.Sprintf("  %s %s = %d; // index=%d kind=%s", f.ProtoType, f.Name, f.Index+1, f.Index, f.WireKind))
	}
	lines = append(lines, "}", "")
	if ec.isSlotItem() {
		lines = append(lines,
			fmt.Sprintf("// Mirrors C++ property_slots encode: { sz, data }"),
			fmt.Sprintf("message %sSlotsSnapshot {", ec.Name),
			"  uint32 sz = 1;",
			fmt.Sprintf("  repeated %sSnapshot data = 2;", ec.Name),
			"}",
			"",
		)
	}
	return strings.Join(lines, "\n")
}

func writeSchemaLuaProto(unit *ir.CompilationUnit, outDir string, legacyWire, copyRuntime bool, runtimeDir string) ([]string, error) {
	schemaDir := filepath.Join(outDir, "schema")
	luaDir := filepath.Join(outDir, "lua")
	protoDir := filepath.Join(outDir, "proto")
	for _, d := range []string{schemaDir, luaDir, protoDir} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return nil, err
		}
	}
	var written []string
	names := sortedClassNames(unit)
	for _, name := range names {
		cls := unit.Classes[name]
		ec := buildEmitClass(cls, legacyWire)
		var fd *ir.FlagsDef
		if cls.FlagsRef != nil {
			fd = unit.Flags[*cls.FlagsRef]
		}
		sp := filepath.Join(schemaDir, name+".schema.json")
		b, _ := json.MarshalIndent(emitSchemaJSON(ec), "", "  ")
		b = append(b, '\n')
		if err := os.WriteFile(sp, b, 0o644); err != nil {
			return nil, err
		}
		written = append(written, sp)

		lp := filepath.Join(luaDir, name+"_meta.lua")
		if err := os.WriteFile(lp, []byte(emitLuaMeta(ec)), 0o644); err != nil {
			return nil, err
		}
		written = append(written, lp)

		rp := filepath.Join(luaDir, name+"_record.lua")
		if err := os.WriteFile(rp, []byte(emitLuaRecord(ec, fd)), 0o644); err != nil {
			return nil, err
		}
		written = append(written, rp)

		pp := filepath.Join(protoDir, name+".proto")
		if err := os.WriteFile(pp, []byte(emitProto(ec)), 0o644); err != nil {
			return nil, err
		}
		written = append(written, pp)
	}
	if copyRuntime {
		root := runtimeDir
		if root == "" {
			root = filepath.Join(findRepoRoot(), "meta", "lua_runtime")
		}
		written = append(written, copyLuaRuntime(luaDir, root)...)
	}
	return written, nil
}

func copyLuaRuntime(luaDir, runtimeSrc string) []string {
	var written []string
	for _, name := range []string{"property_runtime.lua", "property_record.lua", "json.lua"} {
		src := filepath.Join(runtimeSrc, name)
		dst := filepath.Join(luaDir, name)
		b, err := os.ReadFile(src)
		if err != nil {
			continue
		}
		_ = os.WriteFile(dst, b, 0o644)
		written = append(written, dst)
	}
	cmdSrc := filepath.Join(findRepoRoot(), "meta", "mustache", "property_cmd_lua.mustache")
	if b, err := os.ReadFile(cmdSrc); err == nil {
		dst := filepath.Join(luaDir, "property_cmd.lua")
		_ = os.WriteFile(dst, b, 0o644)
		written = append(written, dst)
	}
	return written
}

func sortedClassNames(unit *ir.CompilationUnit) []string {
	names := make([]string, 0, len(unit.Classes))
	for n := range unit.Classes {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

func boolLua(b bool) string {
	if b {
		return "true"
	}
	return "false"
}

func deref(p *string) string {
	if p == nil {
		return ""
	}
	return *p
}

func or(a, b string) string {
	if a == "" {
		return b
	}
	return a
}

func findRepoRoot() string {
	wd, err := os.Getwd()
	if err != nil {
		return "."
	}
	dir := wd
	for {
		if _, err := os.Stat(filepath.Join(dir, "meta", "mustache")); err == nil {
			return dir
		}
		if strings.HasSuffix(filepath.ToSlash(dir), "/tools/psync") {
			return filepath.Dir(filepath.Dir(dir))
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	// binary next to tools/psync
	exe, err := os.Executable()
	if err == nil {
		d := filepath.Dir(exe)
		for i := 0; i < 6; i++ {
			if _, err := os.Stat(filepath.Join(d, "meta", "mustache")); err == nil {
				return d
			}
			d = filepath.Dir(d)
		}
	}
	return wd
}
