package emit

import (
	"path/filepath"
	"strings"
	"unicode"
)

// ProtoPackage is the protobuf package (dot form). Short fixed name for test/examples.
func ProtoPackage(outDir string) string {
	_ = outDir
	return "psync"
}

// ProtoCppNs is the C++ namespace for generated PB types.
func ProtoCppNs(outDir string) string {
	_ = outDir
	return "psync"
}

// ProtoNsTail is the single C++ namespace identifier used in forward decls.
func ProtoNsTail(outDir string) string {
	_ = outDir
	return "psync"
}

// ToSnake converts PascalCase / camelCase to snake_case (Player → player, LoginRecord → login_record).
func ToSnake(s string) string {
	if s == "" {
		return s
	}
	var b strings.Builder
	for i, r := range s {
		if unicode.IsUpper(r) {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(unicode.ToLower(r))
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

// ProtoFileStem is the .proto basename without extension (Player → player).
func ProtoFileStem(className string) string {
	return ToSnake(className)
}

// ProtoUnitName derives a filesystem-safe token from outDir (kept for diagnostics).
func ProtoUnitName(outDir string) string {
	clean := filepath.Clean(outDir)
	base := filepath.Base(clean)
	if base == "generated" || base == "proto" || base == "." || base == string(filepath.Separator) {
		parent := filepath.Dir(clean)
		base = filepath.Base(parent)
	}
	return sanitizeProtoIdent(base)
}

func sanitizeProtoIdent(s string) string {
	if s == "" || s == "." || s == ".." {
		return "generated"
	}
	var b strings.Builder
	for i, r := range s {
		switch {
		case unicode.IsLetter(r) || r == '_':
			b.WriteRune(r)
		case unicode.IsDigit(r):
			if i == 0 {
				b.WriteByte('x')
			}
			b.WriteRune(r)
		case r == '-' || r == '.':
			b.WriteByte('_')
		default:
			b.WriteByte('_')
		}
	}
	out := b.String()
	if out == "" {
		return "generated"
	}
	if c := out[0]; c >= '0' && c <= '9' {
		return "x_" + out
	}
	return out
}

func emitMutateProto(pkg string) string {
	return strings.Join([]string{
		`syntax = "proto3";`,
		"// Shared mutate wire format — auto-generated by psync emit (cmd values match property_cmd).",
		"package " + pkg + ";",
		"",
		"enum PropertyCmd {",
		"  CMD_CLEAR = 0;",
		"  CMD_SET = 1;",
		"  CMD_ADD = 2;",
		"  CMD_ERASE = 3;",
		"  CMD_PUSH = 4;",
		"  CMD_POP = 5;",
		"  CMD_POP_ERASE = 6;",
		"  CMD_ITEM_CHANGE = 7;",
		"  CMD_SLOT_SWAP = 8;",
		"  CMD_SLOT_RESIZE = 9;",
		"  CMD_SLOT_MOVE = 10;",
		"  CMD_UPDATE_FIELDS = 11;",
		"}",
		"",
		"message MutateMsg {",
		"  uint64 offset = 1;",
		"  PropertyCmd cmd = 2;",
		"  uint64 flag = 3;",
		"  // v1: UTF-8 JSON payload compatible with existing any_container encode",
		"  bytes data = 4;",
		"}",
		"",
		"message MutateBatch {",
		"  uint32 schema_version = 1;",
		"  repeated MutateMsg msgs = 2;",
		"}",
		"",
	}, "\n")
}
